### ISSUE TITLE
Error: "Your total amount is not matching with the sum of unit price amounts per quantity"

### ISSUE THREAD

**Issue by ihelpco** [paytabscom/paytabs-woocommerce#4]
Hi @wajihkm,
After installing the new release 3.1.0, our customers received this error when they chose to pay with PayTabs upon checkout:
"Your total amount is not matching with the sum of unit price amounts per quantity"
Thus, we removed it and used the older version of PayTabs plugin.

I really like to know what makes this error, is it counting the amounts without the tax, or because we disabled the Zip Code field from the checkout page?
My client site is alarrab.com .

Thanks

**Comment by wajihkm** [comment]
Hi @ihelpco ,

We apologize for this mistake.
We have fixed it.

Please check the latest release 3.1.1
[https://github.com/paytabscom/paytabs-woocommerce/releases/tag/3.1.1](url)

Thanks

**Comment by ihelpco** [comment]
Hi @wajihkm, Thanks for the fix but the same error still not fixed.

**Comment by wajihkm** [comment]
Hi @ihelpco ,

We are sorry, and apologize to hear that.

Could you please provide us with some information?
the domain, or: taxes, coupons, discounts ... 

Thank you

**Comment by ihelpco** [comment]
Hi @wajihkm,
domain: alarrab.com
taxes are included in the product prices.
Thanks

**Comment by wajihkm** [comment]
Hi @ihelpco ,

Could you please contact the support team at:
support@paytabs.com

Thanks
